ignore package-lock for now, add echos to see why stuck

diff --git a/bin/dv-coding-pre b/bin/dv-coding-pre
--- a/bin/dv-coding-pre
+++ b/bin/dv-coding-pre
@@ -24,11 +24,14 @@ if [ -f "$env" ]; then
 fi
 
 if [ ! -d _to_developer/test-results ]; then
-   dv-test || echo "One or more tests failed"
+    dv-test || echo "One or more tests failed"
+else
+    echo "Re-using existing _to_developer/test-result"
 fi
 
 # Expose recent git commits, which is kind of like chat
 # conversation history.
+echo Including recent commits
 if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
     RECENT_COMMITS=${RECENT_COMMITS:-0}
     mkdir -p _to_developer/recent-commits
@@ -43,13 +46,7 @@ else
     echo WARNING: not using git, so not providing change history to AI
 fi
 
-
-
-# optional web search
-
-# optional experiment
-
-# ...etc
+echo TODO: RUN TOOLS eg curl
 
 rm -rf _from_developer
 mkdir _from_developer
