cleaning up dv-edit

diff --git a/bin/dv-edit b/bin/dv-edit
--- a/bin/dv-edit
+++ b/bin/dv-edit
@@ -102,9 +102,6 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-# somehow left over sometimes :-(
-rm -rf _pre_mime
-
 if [ "$force" = 'false' ]; then
     dv-git-assert-clean
 fi
@@ -113,24 +110,41 @@ dotdv="$(dv-project-dir)/.dv"
 log="$(dv-path-create "$dotdv/edits" edit)"
 mkdir -p "$log"
 abslog=$(realpath "$log")
-log_info "Logging to '$abslog'"
+log_info "dv-edit keeping files in '$abslog'"
 
 rm -f "$dotdv/latest-edit"
 ln -s "$abslog" "$dotdv/latest-edit" # --force does weird things
-log_info "Currenlty also $dotdv/latest-edit"
+# log_info "Currenlty also $dotdv/latest-edit"
 
 infile="$log/to-ai.mime"
 outfile="$log/from-ai.txt"
 out2="$log/from-ai.mime"
 export DV_LOGFILE="$log/events"
+prompt_file="$log/combined_prompt.md"
 
 args=()
 
+function to_snake_case() {
+    echo "$1" | \
+        tr '[:upper:]' '[:lower:]' | \
+        sed -E 's/[^a-zA-Z0-9]+/_/g' | \
+        sed -E 's/^_+|_+$//g'
+}
+
+function add_prompt() {
+    local title="$1"
+    local value="$2"
+    local tag="$(to_snake_case "$title")"
+    log_debug "adding prompt section title '$title' tag '$tag'"
+    args+=("$tag"="$value")
+    echo -e "## $title\n\n$value\n" >> "$prompt_file"
+}
+
 if [ -n "$prompt" ]; then
-    args+=(user-prompt="$prompt")
+    add_prompt "General Instructions" "$prompt"
     echo "$prompt" > "$log/prompt.md"
 else
-    log_error "Missing prompt. Use --prompt or DV_PROMPT or dv-edit-*"
+    log_error "Missing prompt. Use --prompt/-p/-s/-t or DV_PROMPT or dv-edit-*"
     exit 1
 fi
 
@@ -143,9 +157,10 @@ args+=(--ignore=package-lock.json)
 # left out by packmime unless we say this
 if [ -d _to_developer ]; then
     args+=(--include=_to_developer)
+    # Sometimes the tests leave a working_directory we're not allowed to read
+    # or traverse.
+    chmod -Rv u+rX _to_developer > _to_developer/chmod_changes_for_sending.log 2>&1
 fi
-
-# args+=()
 
 # all the passthru args, which should include paths
 if [ ${#c1[@]} -eq 0 ]; then
@@ -155,11 +170,11 @@ fi
 args+=("${c1[@]}")
 
 if [ "$ask" = 'true' ]; then
-    args+=(response_prompt="Please format your response as plain text a terminal.")
+    add_prompt "Response Format" "Please format your response as plain text for display on a terminal."
 else
-    args+=(commit_message_prompt="Please attach a file '$commit_message_file' which is a clearly written, professional git commit message for all the file changes you are now providing. If you are not making any changes, skip this step.")
-    # SEEMS TO USUALLY FAIL args+=(use_patches_prompt="The files you see attached here are the files in the project directory. You can replace any of them by attaching a file to your response using the same pathname. You can make more efficient changes by putting unix patch files in _from_developer/patches. Any file attached with a name like that will be applied as a patch. Please use patches if they will be shorter than attaching the whole file.")
-    args+=(response_prompt="$(< $(dv-path prompts/response-format.md))")
+    add_prompt "Provide Commit Message" "$(dv-prompt-select attach-commit-message | dv-template-fill filename="$commit_message_file")"
+    # BROKEN - add_prompt "Patches May Be Useful" "$(dv-prompt-select use-patch)"
+    add_prompt "Response Format" "$(dv-prompt-select response-format)"
 fi
 
 dv-show-arguments "${args[@]}" > "$log/arguments-for-packmime"
@@ -170,52 +185,77 @@ rm -rf _from_developer
 
 log_info "llpipe starting"
 
-export LLPIPE_LOG_RESPONSE="$log/http-response.txt"
-# echo BEFORE "LLPIPE_LOG_RESPONSE='$LLPIPE_LOG_RESPONSE' llpipe < '$infile' | tee '$outfile'"
-if [ -n "${DV_VERBOSE:-}" ]; then
-    llpipe < "$infile" | tee "$outfile"
-else
-    llpipe < "$infile" > "$outfile"
-fi
+for try in {1..10}; do
+    if [[ $try > 5 ]]; then
+        log_error 'Unable to get Content-Type response from llpipe'
+        exit 1
+    fi
+    
+    export LLPIPE_LOG_RESPONSE="$log/http-response-$try.txt"
+    # echo BEFORE "LLPIPE_LOG_RESPONSE='$LLPIPE_LOG_RESPONSE' llpipe < '$infile' | tee '$outfile'"
 
-log_info "llpipe exit value $?"
+    # should be instead handled with LLPIPE_SHOW
+    if [ -n "${DV_VERBOSE:-}" ]; then
+        llpipe < "$infile" | tee "$outfile"
+    else
+        llpipe < "$infile" > "$outfile"
+    fi
 
-if [ "$ask" = 'true' ]; then
-    log_info "Using 'ask' mode, just outputing response"
-    echo -e "
-================ AI Response ================${GREEN}
+    if [ "$ask" = 'true' ]; then
+        log_info "Using 'ask' mode, just outputing response"
+        echo -e "
+============ ==== AI Response ================${GREEN}
 $(fmt -s $outfile)${NC}
 =============================================
 "
-    exit 0
-fi
+        exit 0
+    fi
 
-# Clean up args a little better?  But we might change args of unpackmime.
-# TODO: define interface a bit better. Like "--patch" should be the default
-# and be called --safe, I think? or --git-safe?
+    if grep -q 'Content-Type:' "$outfile"; then
+        break
+    fi
 
+    # We could be here because the llm gave 0 tokens, due to some kind of
+    # failure, or maybe it just completely misbehaved. In either case, let's
+    # try again a few times.
+
+    save="${outfile}-$try"
+    cp -a "$outfile" "$save"
+    log_warning "Response from llpipe did not include 'Content-Type:', saved as $save"
+    log_debug sleeping a little
+    sleep 5
+done
+    
 if [ "$force" = 'false' ]; then
     c2+=(--patch)
 fi
 
+# seems unnecessary, but I'm trying to track down a bug
+if [ "$force" = 'false' ]; then dv-git-assert-clean; fi
+
+# text before Content-Type goes to _pre_mime, the rest goes to $out2
 awk "/Content-Type:/{p=NR}; p{print > \"$out2\"; next} {print > \"_pre_mime\"}" "$outfile"
+
+if [[ -f commit_message ]]; then
+    echo "error prone: there should not be a file called commit_message in '$PWD'"
+    exit 1
+fi
 
 c2+=("$out2")
 dv-show-arguments "${c2[@]}" > "$log/arguments-for-unpackmime"
 
-unpackmime "${c2[@]}" > "$log/unpack-stdout.txt"
-
-cat "$log/unpack-stdout.txt"
-
-# Some prompts may involved stuff being written here.  Should abstract
-# the name of this, since it might have semantics to some AIs. Like
-# $DIR_FROM_AI and $DIR_TO_AI but with possible quoting issues.
+unpackmime "${c2[@]}" | tee "$log/unpack-stdout.txt"
 
 dv-patch-runner
 
 if [ ! -f "$commit_message_file" ]; then
-    mkdir -p "$(dirname "$commit_message_file")"
-    echo "AI generation failed to produce commit message" > $commit_message_file
+    if [[ -f commit_message ]]; then
+        log_warn 'AI put commit_message in the wrong place, moving'
+        mv commit_message $commit_message_file
+    else
+        mkdir -p "$(dirname "$commit_message_file")"
+        echo "AI generation failed to produce commit message" > $commit_message_file
+    fi
 fi
 
 echo "
@@ -251,14 +291,13 @@ $(< _pre_mime)
     mv _pre_mime "$log"
 fi
 
-# not sure how this could still be here, but it is ?!
-rm -f _pre_mime
-
-# dv_version=$(git -C"$(dv-path)" rev-parse HEAD)
-# echo "# dv version commit $dv_version"
+if [[ -f _pre_mime ]]; then
+    echo _pre_mime still exists here after it should have just been moved
+    exit 1
+fi
 
 if dv-settings --check auto-commit=true; then
     dv-commit
 fi
 
-log_info "Details saved to $log"
+log_info "dv-edit done, logs in '$abslog'"
