bringing package responder to sprints

diff --git a/bin/dv-package-search b/bin/dv-package-search
--- a/bin/dv-package-search
+++ b/bin/dv-package-search
@@ -4,12 +4,16 @@ source $(dv-path lib/common.sh) # -*-mode: sh-mode -*-
 spec="$1"
 me=pkgsearch
 pref="${STRUCT_PREFIX:-${me}_}"
+state="${DV_OUTPUT_TO}" # required to be set by calle
 
 start_dir="$PWD"
 
+# Set DV_RESUME=true to just continue from where you left off in the
+# repo. You might need to roll back the cleanup first.
 if [[ -z "${DV_RESUME:-}" ]]; then
     cell=$(dv-cell-create $me)
     cd "$cell"
+    echo "$PWD" > "$state/cell"
 
     dv-settings auto-commit=true
 
@@ -28,6 +32,21 @@ Suggested search and retrieval commands:
 Other commands may work as well. It is okay to experiment.
 '
 
+function clean_exit() {
+    exit 0
+    ## there's no need to clean up, this is a single-use cell!
+    local commit=''
+    for file in search.sh search-results.txt guide.md package-found.txt package-not-available.txt search-stderr.txt; do
+        if [[ -f "$file" ]]; then
+            rm "$file"
+            git add "$file"
+            commit='git commit -q -m"remove agent coordination files"'
+        fi
+    done
+    eval "$commit"
+    exit 0
+}
+
 for count in {1..5}; do
     log_info "\n\npackage search count = $count\n\n"
     
@@ -39,15 +58,15 @@ for count in {1..5}; do
     if [[ ! -f 'search-results.txt' || 'search.sh' -nt 'search-results.txt' ]]; then
         log_info 'missing or out-of-date search-results.txt -- searching'
         : ${DV_TIMEOUT:=60}
-        timeout --verbose $DV_TIMEOUT bash search.sh 2>&1 | tee search-results.txt
+        timeout --verbose $DV_TIMEOUT bash search.sh 2> search-stderr.txt | tee search-results.txt || true
         log_info "$(wc search*)"
-        git add search-results.txt && git commit -q -m'search results from execution of search.sh'
+        git add search-results.txt search-stderr.txt && git commit -q -m'search results from execution of search.sh'
     fi
     
     if [[ ! -f guide.md ]]; then
         log_info no guide.md
         # extra size of search results
-        dv-edit --maxlen=300000 -T'As an expert software engineer, consider the results provided to the given searches. Does something in these results provide what we need to address the needs expressed in docs/request.md? If so, attach a file guide.md, which consisely explains, with code samples, how to use this package to do essentially what is requested. In this case, also attach a file package-found.txt that contains just the name of the package. At the end of guide, include a brief explanation of why this package is better than alternatives, including any popularity and quality metrics you have.
+        dv-edit --maxlen=300000 -T'As an expert software engineer, consider the results provided to the given searches. Is there a package in these results which provides what we need, as expressed in docs/request.md? If so, attach a file guide.md, which consisely explains, with code samples, how to use this package to do essentially what is requested. (If more than 20 lines of code are needed to adapt this module to our needs, reject it, so that we can handle to situation in a cleaner way.) If we are accepting a module, also attach a file package-found.txt that contains just the name of the package. At the end of guide, include a brief explanation of why this package is better than alternatives, including any popularity and quality metrics you have.
 
 If these search results do not give you enough information to do that with confidence, you have two options.
 
@@ -58,31 +77,29 @@ Or, you can search again. First, explain the journey so far. What was searched f
 
     if [[ -f package-not-available.txt ]]; then
         log_info search agent giving up $PWD
-        echo "${pref}success=''"
-        echo "${pref}name=''"
-        echo "${pref}status='concluded package-not-available on round $count'"
-        echo "${pref}cell='$PWD'"
-        exit 0
+        echo "concluded package-not-available on round $count" > "$state/status"
+        clean_exit
     fi
 
     if [[ -f package-found.txt ]]; then
-        pkg=$(sanitize_id $(<package-found.txt))
-        guide_text="$(printf '%q' "$(<guide.md)")"
+        pkg=$(<package-found.txt)
+        if [[ "$pkg" =~ [^@a-zA-Z0-9_-] ]]; then
+            # we even allow upper case, which they don't
+            echo "Package id violates NPM rules"
+            exit 1
+        fi
         log_info "search agent found package: $pkg"
-        echo "${pref}success=true"
-        echo "${pref}name=$pkg"
-        echo "${pref}guide=$guide_text"
-        echo "${pref}cell='$PWD'"
-        exit 0
+        
+        cp guide.md "$state/guide.md"
+        echo "$pkg" > "$state/name"
+        echo "declared success in round $count" > "$state/status"
+        clean_exit
     fi
 done
 
 log_warning 'still in search loop when limit reached'
 
-echo "${pref}success=''"
-echo "${pref}name=''"
-echo "${pref}status='still searching after round $count'"
-echo "${pref}cell='$PWD'"
-exit 0
+echo "still searching after round $count" > "$state/status"
+clean_exit
     
     
